name: C/C++ CI

on:
  push:
    branches: [ "troika" ]
  pull_request:
    branches: [ "troika" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: CI Build
      run: chmod +x ci-build.sh && ./ci-build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Motorola One Action
        path: ./workspace/kernel
